### ISSUE TITLE
when i try to connect to mc3p server proxy

### ISSUE THREAD

**Issue by botiapa** [mmcgill/mc3p#14]
i get this error 

ERROR:mc3p:MinecraftProxy for client caught exception, out of sync
ERROR:mc3p:Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\mc3p-master\mc3p\proxy.py", line 169, in h
andle_read
    packet = parse_packet(self.stream, self.msg_spec, self.side)
  File "C:\Python27\lib\site-packages\mc3p-master\mc3p\proxy.py", line 233, in p
arse_packet
    raise UnsupportedPacketException(msgtype)
UnsupportedPacketException: Unsupported packet id 0x10

**Comment by whamer100** [comment]
I get the same error
